default:
  image: registry.gitlab.com/basiliqio/dockerfiles

variables:
  RUSTFLAGS: -C link-dead-code

stages:
  - test

build_and_test_rust:
  stage: test
  before_script:
    - mkdir -p .git/hooks
    - export NAME=messy_json
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
    - cargo build --all-targets --all-features
    - cargo test --all-features
  after_script:
    - for file in $(find target/debug/deps -executable \( -name "$(basename messy_json)-*" -o -name "mod-*" \) );
      do
        echo "Running $file";
        mkdir -p "target/cov/$(basename $file)";
        cp $file $(basename $file);
        kcov "target/cov/$(basename $file)" --exclude-pattern="/.cargo,/usr/lib,$PWD/src/tests,$PWD/tests" $(basename $file);
      done
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -s target/cov
